### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by Kaikina** [ArcticZeroo/self-slack-bot#1]
Hello,

I'm really sorry to bother you with that small issue, but I can't get your self bot working...
I created the tokens.js file in config/
And wrote that : 
```
module.exports = {
    me: 'xoxp-xxxxxxxxx-xxxxxxx-xxxxxxxx-xxxxxxxxxxxxxxxxxx'
}
```
(The token I got from Slack)

But when I run the bot (node main), it just sends me the error : 
![image](https://user-images.githubusercontent.com/14168333/33206805-c1e739fc-d10b-11e7-929f-59eed347087d.png)

Do you know what is happening ?

**Comment by ArcticZeroo** [comment]
What version of node are you using? You need 7.6+ for async features.

**Comment by Kaikina** [comment]
Thanks for your answer. Indeed, it was my Node version.
But now, I've a new error about a not found module : keys ?
![image](https://user-images.githubusercontent.com/14168333/33258589-6a9148ea-d35a-11e7-81cc-d857afa07498.png)

**Comment by Kaikina** [comment]
By creating an empty file keys.js, it seems to work..

**Comment by ArcticZeroo** [comment]
Hmm, not sure why I had that required. I think I planned to add a youtube video command of some sort. It's removed now if you re-pull.
